In [3]:
import numpy as np

In [3]:
a=np.array([1,2,3]) # create an array from a list
print('Array a:',a)

Array a: [1 2 3]


In [7]:
# Create an array with evenly spaced values
b=np.arange(0,10,2) # Values from 0-10 with step count 2
print('Array b:',b)

Array b: [0 2 4 6 8]


In [9]:
# create an array with linearly spaced values
c=np.linspace(0,1,5) # 5 values evenly spaced between 0 and 1
print('Array c:',c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [11]:
# Create an array filled with zeros
d=np.zeros((2,3)) # 2x3 array of zeros
print('Array d:\n',d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Create an array filled with ones
e=np.ones((3,2)) # 3x2 array of ones
print('Array e:\n',e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
# Create an idendtity matrix
f=np.eye(3) # 3x3 identity matrix
print('Identity Matrix f:\n',f)

Identity Matrix f:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Array Manipulation Functions

In [23]:
# Reshape an array
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3)) # Reshape to 1x3 matrix
print('Reshaped Array:',reshaped)

Reshaped Array: [[1 2 3]]


In [25]:
# Flatten an array
f1=np.array([[1,2],[3,4]])
flattend=np.ravel(f1) # Flattend to 1D array
print('Flattend Array:',flattend)

Flattend Array: [1 2 3 4]


In [35]:
# Transpose an array
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1) # Transpose array
print('Transposed Array e1:\n',transposed)

Transposed Array e1:
 [[1 3]
 [2 4]]


In [33]:
# Stack Arrays Vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2]) # stack a and b verticalically
print('Stacked Array:\n', stacked)

Stacked Array:
 [[1 2]
 [3 4]]


Mathematical Functions

In [37]:
# Add two arrays
g=np.array([1,2,3,4])
added=np.add(g,2) # add 2 to each element
print('Added 2 to g:',added)

Added 2 to g: [3 4 5 6]


In [39]:
square=np.power(g,2) # Square each element
print('Squared g:',square)

Squared g: [ 1  4  9 16]


In [41]:
sqrt=np.sqrt(g) # square root of g
print('Square root of g:',sqrt)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [43]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [45]:
a2=np.array([1,2,3])
dot_product=np.dot(a2,g)
doy_product

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [47]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [49]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print('Dot product of a and a1:',dot_product)

Dot product of a and a1: 14


Statistical Functions

In [51]:
s=np.array([1,2,3,4])
mean=np.mean(s) # Average or Mean of s
print('Mean of s:',mean)

Mean of s: 2.5


In [55]:
# Standard deviation of s
std_dev=np.std(s)
print('Standard Deviation of s:',std_dev)

Standard Deviation of s: 1.118033988749895


In [57]:
#minimum elemet of an array
min=np.min(s)
print('Min of s:',min)

Min of s: 1


In [59]:
#maximum elemet of an array
max=np.max(s)
print('Max of s:',max)

Max of s: 4


Linear Algebra Functions

In [63]:
# Create a matrix
mat=np.array([[1,2],[3,4]])
mat

array([[1, 2],
       [3, 4]])

In [65]:
# Determinant of a matrix
determinant=np.linalg.det(mat)
print('Determinent of Matrix:',determinant)

Determinent of Matrix: -2.0000000000000004


In [67]:
# Inverse of the matrix
inverse=np.linalg.inv(mat)
print('Inverse of Matrix:\n',inverse)

Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Random Sampling Functions

In [5]:
# Generate random values between 0 and 1
random_vals=np.random.rand(3) # Array of 3 random values between 0 and 1
print('Random Values:',random_vals)

Random Values: [0.2196585  0.6555345  0.13716604]


In [7]:
# Set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [13]:
# generate random integers
rand_int=np.random.randint(0,10,size=5)
print('Random Integers:',rand_int)

Random Integers: [9 3 5 2 4]


In [15]:
np.random.seed(0)

rand_int=np.random.randint(0,10,size=5)
print('Random Integers:',rand_int)

Random Integers: [5 0 3 3 7]


Boolean and Logical Functions

In [19]:
#Check if all elements are True
#all
logical_test=np.array([True,False,True])
all_true=np.all(logical_test)
print('All elements True:',all_true)

All elements True: False


In [21]:
logical_test=np.array([True,True,True])
all_true=np.all(logical_test)
print('All elements True:',all_true)

All elements True: True


In [23]:
logical_test=np.array([False,False,False])
all_true=np.all(logical_test)
print('All elements True:',all_true)

All elements True: False


In [27]:
# Check if any elemets are True
logical_test=np.array([True, False,True])
any_true=np.any(logical_test)
print('All elements True:',any_true)

All elements True: True


Set Operations

In [29]:
# Intersection of two arrays
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print('Intersection of a and b:',intersection)

Intersection of a and b: [3 4]


In [31]:
#Union of Two arrays
union=np.union1d(set_a,set_b)
print('Union of a and b:',union)

Union of a and b: [1 2 3 4 5 6]


Array Attribute Functions

In [34]:
a=np.array([1,2,3])
shape=a.shape # Shape of Array
size=a.size # Number of elements
dimensions=a.ndim # Number of dimensions
dtype=a.dtype # Data type of array

print('Shape of a:',shape)
print('Size of a:',size)
print('Dimensions of a:',dimensions)
print('Data Type of a:',dtype)

Shape of a: (3,)
Size of a: 3
Dimensions of a: 1
Data Type of a: int64


Other Functions

In [36]:
# create a copy of an Array
a=np.array([1,2,3])
copied_array=np.copy(a)
print('Copied array:',copied_array)

Copied array: [1 2 3]


In [38]:
# Size of bytes in array
array_size_in_bytes=a.nbytes
print('Size of a in Bytes:',array_size_in_bytes)

Size of a in Bytes: 24


In [40]:
# Check if two arrays share memory
shared=np.shares_memory(a,copied_array)
print('Do a and copied_array share memory:',shared)

Do a and copied_array share memory: False
