Numpy

In [1]:
import numpy as np

In [5]:
np.__version__ # there are teo underscores

'1.26.4'

In [7]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ]'

Creating Arrays

In [9]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

# we are converting list to array

In [13]:
arr=np.array(my_list)

In [15]:
arr

array([0, 1, 2, 3, 4, 5])

In [17]:
type(arr)

numpy.ndarray

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(3.0)

array([0., 1., 2.])

In [25]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(10,20,5)

array([10, 15])

In [31]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [33]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [35]:
ar=np.arange(-20,10)
ar

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(10,10)

array([], dtype=int64)

In [39]:
np.arange()

TypeError: arange() requires stop to be specified.

In [41]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [43]:
np.zeros(3, dtype=int) #hyperparameter tunning

array([0, 0, 0])

In [45]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [51]:
np.zeros((2,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [57]:
np.ones((3), dtype=int)

array([1, 1, 1])

In [59]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
rand(3,2)

NameError: name 'rand' is not defined

In [68]:
np.random.rand(5)

array([0.87297307, 0.8656112 , 0.0152346 , 0.44008299, 0.84176732])

In [72]:
np.random.rand(2,3)

array([[0.5828521 , 0.80665582, 0.96383098],
       [0.35423653, 0.25548442, 0.99490942]])

In [76]:
np.random.randint(2,3)

2

In [86]:
np.random.randint(5,7)

5

In [90]:
np.random.randint(10,20,5)

array([14, 12, 11, 11, 15])

In [92]:
np.random.randint(10,20,3)

array([18, 13, 15])

In [94]:
np.random.randint(-30,20,10)

array([ -3,   5, -25,   6, -18,   3, -23,   0, -26,   9])