Numpy

In [16]:
import numpy as np

In [5]:
np.__version__ # there are teo underscores

'1.26.4'

In [7]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 08:22:19) [Clang 14.0.6 ]'

Creating Arrays

In [58]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

# we are converting list to array

In [60]:
arr=np.array(my_list)

In [62]:
arr

array([0, 1, 2, 3, 4, 5])

In [17]:
type(arr)

numpy.ndarray

In [21]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(3.0)

array([0., 1., 2.])

In [25]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(10,20,5)

array([10, 15])

In [31]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [33]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [35]:
ar=np.arange(-20,10)
ar

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(10,10)

array([], dtype=int64)

In [39]:
np.arange()

TypeError: arange() requires stop to be specified.

In [41]:
np.zeros(3) # parameter tunning

array([0., 0., 0.])

In [43]:
np.zeros(3, dtype=int) #hyperparameter tunning

array([0, 0, 0])

In [45]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [51]:
np.zeros((2,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [57]:
np.ones((3), dtype=int)

array([1, 1, 1])

In [59]:
np.ones(4)

array([1., 1., 1., 1.])

In [64]:
rand(3,2)

NameError: name 'rand' is not defined

In [68]:
np.random.rand(5)

array([0.87297307, 0.8656112 , 0.0152346 , 0.44008299, 0.84176732])

In [72]:
np.random.rand(2,3)

array([[0.5828521 , 0.80665582, 0.96383098],
       [0.35423653, 0.25548442, 0.99490942]])

In [76]:
np.random.randint(2,3)

2

In [86]:
np.random.randint(5,7)

5

In [90]:
np.random.randint(10,20,5)

array([14, 12, 11, 11, 15])

In [92]:
np.random.randint(10,20,3)

array([18, 13, 15])

In [94]:
np.random.randint(-30,20,10)

array([ -3,   5, -25,   6, -18,   3, -23,   0, -26,   9])

In [5]:
np.random.randint(10,40,(10,10)) # Generates random elements between 10-40 with 10*10 matrix

array([[30, 13, 15, 10, 11, 36, 28, 36, 37, 26],
       [16, 19, 21, 10, 18, 11, 34, 22, 15, 38],
       [16, 10, 17, 14, 26, 28, 22, 39, 12, 20],
       [31, 23, 31, 27, 39, 32, 25, 13, 34, 12],
       [37, 27, 29, 25, 22, 35, 35, 21, 25, 28],
       [14, 32, 32, 38, 17, 13, 29, 22, 39, 33],
       [11, 39, 25, 19, 23, 27, 29, 31, 20, 16],
       [15, 12, 13, 12, 17, 31, 12, 26, 38, 10],
       [34, 19, 33, 30, 11, 21, 36, 32, 17, 23],
       [21, 15, 19, 11, 11, 24, 26, 22, 28, 11]])

In [7]:
np.random.randint(1,20,(3,3))

array([[14,  2, 12],
       [ 1,  9, 15],
       [10, 10,  5]])

In [9]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

Slicing in Matrix

In [22]:
b=np.random.randint(10,20,(5,4))
b

array([[10, 15, 11, 17],
       [18, 15, 10, 17],
       [16, 13, 11, 15],
       [10, 14, 12, 14],
       [19, 15, 13, 19]])

In [24]:
type(b)

numpy.ndarray

In [26]:
b

array([[10, 15, 11, 17],
       [18, 15, 10, 17],
       [16, 13, 11, 15],
       [10, 14, 12, 14],
       [19, 15, 13, 19]])

In [28]:
b[:]

array([[10, 15, 11, 17],
       [18, 15, 10, 17],
       [16, 13, 11, 15],
       [10, 14, 12, 14],
       [19, 15, 13, 19]])

In [30]:
b[1:3]

array([[18, 15, 10, 17],
       [16, 13, 11, 15]])

In [32]:
b

array([[10, 15, 11, 17],
       [18, 15, 10, 17],
       [16, 13, 11, 15],
       [10, 14, 12, 14],
       [19, 15, 13, 19]])

In [34]:
b[1,2]

10

In [36]:
b

array([[10, 15, 11, 17],
       [18, 15, 10, 17],
       [16, 13, 11, 15],
       [10, 14, 12, 14],
       [19, 15, 13, 19]])

In [38]:
b[1,3]

17

In [40]:
b[1,-1]

17

In [42]:
b[2:3]

array([[16, 13, 11, 15]])

In [44]:
b[0:-2]

array([[10, 15, 11, 17],
       [18, 15, 10, 17],
       [16, 13, 11, 15]])

In [46]:
b[0,2]

11

In [48]:
b[-5,-2]

11

Operations

In [50]:
a=np.random.randint(10,20,10)
a

array([11, 19, 15, 17, 17, 18, 13, 11, 10, 16])

In [52]:
id(a)

5253077520

In [64]:
arr

array([0, 1, 2, 3, 4, 5])

In [68]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[78, 59, 56, 61, 86, 55, 76, 95, 84, 49],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69],
       [89, 30, 10, 27, 10, 10, 42, 71, 74, 68],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2],
       [98, 80, 98, 17, 53, 52,  1, 57, 14,  0],
       [89, 66, 13,  0,  4, 33,  9, 95, 96, 95],
       [12, 20,  3, 75, 97, 50, 34, 34, 66, 56]])

In [70]:
arr[:4]

array([0, 1, 2, 3])

In [72]:
arr2[:]

array([[78, 59, 56, 61, 86, 55, 76, 95, 84, 49],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69],
       [89, 30, 10, 27, 10, 10, 42, 71, 74, 68],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2],
       [98, 80, 98, 17, 53, 52,  1, 57, 14,  0],
       [89, 66, 13,  0,  4, 33,  9, 95, 96, 95],
       [12, 20,  3, 75, 97, 50, 34, 34, 66, 56]])

In [74]:
arr2[0:5]

array([[78, 59, 56, 61, 86, 55, 76, 95, 84, 49],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69],
       [89, 30, 10, 27, 10, 10, 42, 71, 74, 68],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37]])

In [76]:
arr2[::-1]

array([[12, 20,  3, 75, 97, 50, 34, 34, 66, 56],
       [89, 66, 13,  0,  4, 33,  9, 95, 96, 95],
       [98, 80, 98, 17, 53, 52,  1, 57, 14,  0],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [89, 30, 10, 27, 10, 10, 42, 71, 74, 68],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69],
       [78, 59, 56, 61, 86, 55, 76, 95, 84, 49]])

In [80]:
arr2[::-2]

array([[12, 20,  3, 75, 97, 50, 34, 34, 66, 56],
       [98, 80, 98, 17, 53, 52,  1, 57, 14,  0],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69]])

In [82]:
arr2[::-3]

array([[12, 20,  3, 75, 97, 50, 34, 34, 66, 56],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [78, 59, 56, 61, 86, 55, 76, 95, 84, 49]])

In [84]:
arr2

array([[78, 59, 56, 61, 86, 55, 76, 95, 84, 49],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69],
       [89, 30, 10, 27, 10, 10, 42, 71, 74, 68],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2],
       [98, 80, 98, 17, 53, 52,  1, 57, 14,  0],
       [89, 66, 13,  0,  4, 33,  9, 95, 96, 95],
       [12, 20,  3, 75, 97, 50, 34, 34, 66, 56]])

In [86]:
arr2[:-3]

array([[78, 59, 56, 61, 86, 55, 76, 95, 84, 49],
       [ 0, 14, 96, 22, 68, 24, 84, 13, 80, 69],
       [89, 30, 10, 27, 10, 10, 42, 71, 74, 68],
       [36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2]])

In [88]:
arr2[3:]

array([[36,  4, 73, 31, 46, 81, 90, 90, 81, 68],
       [52, 36, 24, 59, 69, 81, 54, 58, 96, 37],
       [63, 51,  3, 70,  7, 27, 60, 42, 41,  0],
       [75, 52, 82, 47, 35, 70, 19, 48, 17,  2],
       [98, 80, 98, 17, 53, 52,  1, 57, 14,  0],
       [89, 66, 13,  0,  4, 33,  9, 95, 96, 95],
       [12, 20,  3, 75, 97, 50, 34, 34, 66, 56]])

In [90]:
arr.max()

5

In [92]:
arr.min()

0

In [94]:
arr

array([0, 1, 2, 3, 4, 5])

In [96]:
arr.mean()

2.5

In [98]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [100]:
from numpy import *
a=array([1,2,3,4,9])
median(a)

3.0

Reshaping

In [102]:
arr

array([0, 1, 2, 3, 4, 5])

In [104]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
arr.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [108]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [112]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

Indexing

In [114]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
row=4
col=5

In [118]:
row

4

In [120]:
col

5

In [122]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[row,col]

45

In [126]:
mat[4,5]

45

In [128]:
mat[6] # specific row

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [130]:
mat[:,6] # specific column

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [132]:
mat[:,4] 

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [134]:
mat[row,:] # specific row

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [136]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [138]:
mat[2:6,2:4] # 2:6 --> row part // 2:4 --> column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [140]:
mat[1:2,1:3]

array([[11, 12]])

In [142]:
mat[2:3,2:3]

array([[22]])

Masking

In [144]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [146]:
id(mat)

5247690832

In [148]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [150]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [152]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [154]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [156]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [158]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])